### ISSUE TITLE
Crashes when "sure" is pressed in the dialog box

### ISSUE THREAD

**Issue by amadhuri** [shaileshmamgain5/TwoStageRate#7]
In the dialog "Would you like to post...." it crashes when sure is pressed. I see that it tries to launch an activity with intent to app store. 

final Intent intentToAppstore = settings.getStoreType() == Settings.StoreType.GOOGLEPLAY ?
                        IntentHelper.createIntentForGooglePlay(context) : IntentHelper.createIntentForAmazonAppstore(context);
                context.startActivity(intentToAppstore);d

How can I handle this?

**Comment by shaileshmamgain5** [comment]
Could you share the stack trace?

**Comment by dmitriynet** [comment]
10-30 13:26:19.528 27027-27027/net.******* D/AndroidRuntime: Shutting down VM
10-30 13:26:19.528 27027-27027/net.******* E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.*******, PID: 27027
    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://play.google.com/... pkg=com.android.vending }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1798)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
        at android.app.Activity.startActivityForResult(Activity.java:3917)
        at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
        at android.app.Activity.startActivityForResult(Activity.java:3877)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:744)
        at android.app.Activity.startActivity(Activity.java:4200)
        at android.app.Activity.startActivity(Activity.java:4168)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
        at com.morsebyte.shailesh.twostagerating.TwoStageRate$4.onClick(TwoStageRate.java:291)
        at android.view.View.performClick(View.java:5198)
        at android.view.View$PerformClick.run(View.java:21147)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
